### PR TITLE
Add global CSS file and import functionality

### PR DESCRIPTION
**Pull request by milofultz**
This adds a `style.css` file to the client folder, which is a global CSS file we can use to do the **minimal** styling needed to make iterating a bit more bearable for our respective components.

### CODE REVIEW

**Comment by NylonEric** [comment]
I already added some css into a styles.css file. Do you want to merge those with your branch and re-submit?

Also: Are there any performance differences with loading the css into the react component vs. keeping in the public folder?

**Comment by milofultz** [comment]
> I already added some css into a styles.css file. Do you want to merge those with your branch and re-submit?
> 
> Also: Are there any performance differences with loading the css into the react component vs. keeping in the public folder?

I figured keeping the CSS with the rest of the bundle felt right. Considering we're bundling the HTML and Javascript. Seems like it centralizes all the stuff the site needs into one clump, which is nice.

**Comment by milofultz** [comment]
Oh yeah, if you want to merge your CSS in, go for it! I made this just so we had a central space that it will be pulled in from

**Review by griseldasanchez — APPROVED** [review]
Approved!

**Pull request merged**
